### PR TITLE
fix enable button for spree

### PR DESCRIPTION
**Pull request by puckbag**
Possible solution for resolving #38 

Disclaimer: Ruby newbie so take it for what it is.

### CODE REVIEW

**Comment by pboling** [comment]
Well, it passed travis, so hopefully it doesn't break rails 3.2 compatibility.  Will check tomorrow.

**Comment by phoenixek12** [comment]
But this wont work on nothing but rails, right? I ment this gem should not be rails dependant

**Comment by pboling** [comment]
That is absolutely the goal.  Should work on vanilla rack and any rack based framework.  I just don't have much spare development time at the moment.

**Comment by pboling** [comment]
@phoenixek12 - I have rewritten the enable button class entirely, and released a new version of the gem, 0.6.2.  **ALL** of the specs in the gem are written against a Sinatra setup, so the gem is absolutely not Rails dependent.

**Pull request merged**
